dist: trusty
language: python
jobs:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_pygments=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- pip install pydiatra $pyflakes
- $if_pygments pip install restructuredtext-lint pygments
script:
- ./tiocsti-test echo eggs
- python -m pydiatra .
- pyflakes .
- $if_pygments restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
